// <auto-generated />
using System;
using Lis.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Lis.Persistence.Migrations
{
    [DbContext(typeof(LisDbContext))]
    [Migration("20260508180000_add_agent_provider")]
    partial class add_agent_provider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lis.Persistence.Entities.AgentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompactionThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("compaction_threshold")
                        .HasJsonPropertyName("compaction_threshold");

                    b.Property<int>("ContextBudget")
                        .HasColumnType("integer")
                        .HasColumnName("context_budget")
                        .HasJsonPropertyName("context_budget");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("display_name")
                        .HasJsonPropertyName("display_name");

                    b.Property<string>("ExecSecurity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("exec_security")
                        .HasJsonPropertyName("exec_security");

                    b.Property<int>("ExecTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("exec_timeout_seconds")
                        .HasJsonPropertyName("exec_timeout_seconds");

                    b.Property<string>("GroupContextPrompt")
                        .HasColumnType("text")
                        .HasColumnName("group_context_prompt")
                        .HasJsonPropertyName("group_context_prompt");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default")
                        .HasJsonPropertyName("is_default");

                    b.Property<int>("KeepRecentTokens")
                        .HasColumnType("integer")
                        .HasColumnName("keep_recent_tokens")
                        .HasJsonPropertyName("keep_recent_tokens");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens")
                        .HasJsonPropertyName("max_tokens");

                    b.Property<string>("MentionTriggers")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("mention_triggers")
                        .HasJsonPropertyName("mention_triggers");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model")
                        .HasJsonPropertyName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("provider")
                        .HasJsonPropertyName("provider");

                    b.Property<string>("ThinkingEffort")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("thinking_effort")
                        .HasJsonPropertyName("thinking_effort");

                    b.Property<int>("ToolKeepThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("tool_keep_threshold")
                        .HasJsonPropertyName("tool_keep_threshold");

                    b.Property<bool>("ToolNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("tool_notifications")
                        .HasJsonPropertyName("tool_notifications");

                    b.Property<string>("ToolProfile")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tool_profile")
                        .HasJsonPropertyName("tool_profile");

                    b.Property<int>("ToolPruneThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("tool_prune_threshold")
                        .HasJsonPropertyName("tool_prune_threshold");

                    b.Property<string>("ToolSummarizationPolicy")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("tool_summarization_policy")
                        .HasJsonPropertyName("tool_summarization_policy");

                    b.Property<string>("ToolsAllow")
                        .HasColumnType("text")
                        .HasColumnName("tools_allow")
                        .HasJsonPropertyName("tools_allow");

                    b.Property<string>("ToolsDeny")
                        .HasColumnType("text")
                        .HasColumnName("tools_deny")
                        .HasJsonPropertyName("tools_deny");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.Property<string>("WorkspacePath")
                        .HasColumnType("text")
                        .HasColumnName("workspace_path")
                        .HasJsonPropertyName("workspace_path");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatAllowedSenderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sender_id")
                        .HasJsonPropertyName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ChatId", "SenderId")
                        .IsUnique();

                    b.ToTable("chat_allowed_sender");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<string>("Channel")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel")
                        .HasJsonPropertyName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<long?>("CurrentSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_session_id")
                        .HasJsonPropertyName("current_session_id");

                    b.Property<int?>("DebounceMs")
                        .HasColumnType("integer")
                        .HasColumnName("debounce_ms")
                        .HasJsonPropertyName("debounce_ms");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled")
                        .HasJsonPropertyName("enabled");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.Property<int?>("GroupContextMessages")
                        .HasColumnType("integer")
                        .HasColumnName("group_context_messages")
                        .HasJsonPropertyName("group_context_messages");

                    b.Property<string>("GroupTopic")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("group_topic")
                        .HasJsonPropertyName("group_topic");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group")
                        .HasJsonPropertyName("is_group");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<bool>("OpenGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("open_group")
                        .HasJsonPropertyName("open_group");

                    b.Property<bool>("RequireMention")
                        .HasColumnType("boolean")
                        .HasColumnName("require_mention")
                        .HasJsonPropertyName("require_mention");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CurrentSessionId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("chat");
                });
#pragma warning restore 612, 618
        }
    }
}
