// <auto-generated />
using System;
using Lis.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Lis.Persistence.Migrations
{
    [DbContext(typeof(LisDbContext))]
    [Migration("20260518110654_add_tool_digest_table")]
    partial class add_tool_digest_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lis.Persistence.Entities.AgentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CompactionThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("compaction_threshold")
                        .HasJsonPropertyName("compaction_threshold");

                    b.Property<int>("ContextBudget")
                        .HasColumnType("integer")
                        .HasColumnName("context_budget")
                        .HasJsonPropertyName("context_budget");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("display_name")
                        .HasJsonPropertyName("display_name");

                    b.Property<string>("ExecSecurity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("exec_security")
                        .HasJsonPropertyName("exec_security");

                    b.Property<int>("ExecTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("exec_timeout_seconds")
                        .HasJsonPropertyName("exec_timeout_seconds");

                    b.Property<string>("GroupContextPrompt")
                        .HasColumnType("text")
                        .HasColumnName("group_context_prompt")
                        .HasJsonPropertyName("group_context_prompt");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default")
                        .HasJsonPropertyName("is_default");

                    b.Property<int>("KeepRecentTokens")
                        .HasColumnType("integer")
                        .HasColumnName("keep_recent_tokens")
                        .HasJsonPropertyName("keep_recent_tokens");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens")
                        .HasJsonPropertyName("max_tokens");

                    b.Property<string>("MentionTriggers")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("mention_triggers")
                        .HasJsonPropertyName("mention_triggers");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model")
                        .HasJsonPropertyName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("provider")
                        .HasJsonPropertyName("provider");

                    b.Property<string>("ThinkingEffort")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("thinking_effort")
                        .HasJsonPropertyName("thinking_effort");

                    b.Property<int>("ToolKeepThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("tool_keep_threshold")
                        .HasJsonPropertyName("tool_keep_threshold");

                    b.Property<bool>("ToolNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("tool_notifications")
                        .HasJsonPropertyName("tool_notifications");

                    b.Property<string>("ToolProfile")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tool_profile")
                        .HasJsonPropertyName("tool_profile");

                    b.Property<int>("ToolPruneThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("tool_prune_threshold")
                        .HasJsonPropertyName("tool_prune_threshold");

                    b.Property<string>("ToolSummarizationPolicy")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("tool_summarization_policy")
                        .HasJsonPropertyName("tool_summarization_policy");

                    b.Property<string>("ToolsAllow")
                        .HasColumnType("text")
                        .HasColumnName("tools_allow")
                        .HasJsonPropertyName("tools_allow");

                    b.Property<string>("ToolsDeny")
                        .HasColumnType("text")
                        .HasColumnName("tools_deny")
                        .HasJsonPropertyName("tools_deny");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.Property<string>("WorkspacePath")
                        .HasColumnType("text")
                        .HasColumnName("workspace_path")
                        .HasJsonPropertyName("workspace_path");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatAllowedSenderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sender_id")
                        .HasJsonPropertyName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ChatId", "SenderId")
                        .IsUnique();

                    b.ToTable("chat_allowed_sender");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<string>("Channel")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel")
                        .HasJsonPropertyName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<long?>("CurrentSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_session_id")
                        .HasJsonPropertyName("current_session_id");

                    b.Property<int?>("DebounceMs")
                        .HasColumnType("integer")
                        .HasColumnName("debounce_ms")
                        .HasJsonPropertyName("debounce_ms");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled")
                        .HasJsonPropertyName("enabled");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.Property<int?>("GroupContextMessages")
                        .HasColumnType("integer")
                        .HasColumnName("group_context_messages")
                        .HasJsonPropertyName("group_context_messages");

                    b.Property<string>("GroupTopic")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("group_topic")
                        .HasJsonPropertyName("group_topic");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group")
                        .HasJsonPropertyName("is_group");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<bool>("OpenGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("open_group")
                        .HasJsonPropertyName("open_group");

                    b.Property<bool>("RequireMention")
                        .HasColumnType("boolean")
                        .HasColumnName("require_mention")
                        .HasJsonPropertyName("require_mention");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CurrentSessionId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("chat");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactIdentifierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel")
                        .HasJsonPropertyName("channel");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id")
                        .HasJsonPropertyName("contact_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("Channel", "ExternalId")
                        .IsUnique();

                    b.ToTable("contact_identifier");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ExecAllowlistEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("LastCommand")
                        .HasColumnType("text")
                        .HasColumnName("last_command")
                        .HasJsonPropertyName("last_command");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at")
                        .HasJsonPropertyName("last_used_at");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern")
                        .HasJsonPropertyName("pattern");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Pattern")
                        .IsUnique();

                    b.ToTable("exec_allowlist");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ExecApprovalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<string>("ApprovalId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("approval_id")
                        .HasJsonPropertyName("approval_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command")
                        .HasJsonPropertyName("command");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Cwd")
                        .HasColumnType("text")
                        .HasColumnName("cwd")
                        .HasJsonPropertyName("cwd");

                    b.Property<string>("Decision")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("decision")
                        .HasJsonPropertyName("decision");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasJsonPropertyName("expires_at");

                    b.Property<string>("MessageExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("message_external_id")
                        .HasJsonPropertyName("message_external_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at")
                        .HasJsonPropertyName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resolved_by")
                        .HasJsonPropertyName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status")
                        .HasJsonPropertyName("status");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ApprovalId")
                        .IsUnique();

                    b.HasIndex("ChatId");

                    b.HasIndex("MessageExternalId");

                    b.HasIndex("Status")
                        .HasFilter("status = 'pending'");

                    b.ToTable("exec_approval");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MemoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_id")
                        .HasJsonPropertyName("contact_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasJsonPropertyName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ContactId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("memory");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body")
                        .HasJsonPropertyName("body");

                    b.Property<int?>("CacheCreationTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_creation_tokens")
                        .HasJsonPropertyName("cache_creation_tokens");

                    b.Property<int?>("CacheReadTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_read_tokens")
                        .HasJsonPropertyName("cache_read_tokens");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id")
                        .HasJsonPropertyName("external_id");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens")
                        .HasJsonPropertyName("input_tokens");

                    b.Property<bool>("IsFromMe")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_me")
                        .HasJsonPropertyName("is_from_me");

                    b.Property<string>("MediaCaption")
                        .HasColumnType("text")
                        .HasColumnName("media_caption")
                        .HasJsonPropertyName("media_caption");

                    b.Property<byte[]>("MediaData")
                        .HasColumnType("bytea")
                        .HasColumnName("media_data");

                    b.Property<string>("MediaMimeType")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("media_mime_type")
                        .HasJsonPropertyName("media_mime_type");

                    b.Property<string>("MediaType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("media_type")
                        .HasJsonPropertyName("media_type");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens")
                        .HasJsonPropertyName("output_tokens");

                    b.Property<bool>("Queued")
                        .HasColumnType("boolean")
                        .HasColumnName("queued")
                        .HasJsonPropertyName("queued");

                    b.Property<string>("ReplyContent")
                        .HasColumnType("text")
                        .HasColumnName("reply_content")
                        .HasJsonPropertyName("reply_content");

                    b.Property<string>("ReplyToId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("reply_to_id")
                        .HasJsonPropertyName("reply_to_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("role")
                        .HasJsonPropertyName("role");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sender_id")
                        .HasJsonPropertyName("sender_id");

                    b.Property<string>("SenderName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("sender_name")
                        .HasJsonPropertyName("sender_name");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasJsonPropertyName("session_id");

                    b.Property<string>("SkContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("sk_content")
                        .HasJsonPropertyName("sk_content");

                    b.Property<int?>("ThinkingTokens")
                        .HasColumnType("integer")
                        .HasColumnName("thinking_tokens")
                        .HasJsonPropertyName("thinking_tokens");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasJsonPropertyName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"external_id\" IS NOT NULL");

                    b.HasIndex("ChatId", "Timestamp");

                    b.HasIndex("SenderId", "Id");

                    b.HasIndex("SenderName", "Id");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("message");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.PromptSectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasJsonPropertyName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled")
                        .HasJsonPropertyName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasJsonPropertyName("sort_order");

                    b.Property<string>("Tags")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("tags")
                        .HasJsonPropertyName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Name")
                        .IsUnique();

                    b.ToTable("prompt_section");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ScheduledTaskEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel")
                        .HasJsonPropertyName("channel");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("CreatorSenderId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("creator_sender_id")
                        .HasJsonPropertyName("creator_sender_id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cron_expression")
                        .HasJsonPropertyName("cron_expression");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled")
                        .HasJsonPropertyName("enabled");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at")
                        .HasJsonPropertyName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at")
                        .HasJsonPropertyName("next_run_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload")
                        .HasJsonPropertyName("payload");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("timezone")
                        .HasJsonPropertyName("timezone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("type")
                        .HasJsonPropertyName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("NextRunAt");

                    b.ToTable("scheduled_task");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id")
                        .HasJsonPropertyName("chat_id");

                    b.Property<long>("ContextTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("context_tokens")
                        .HasJsonPropertyName("context_tokens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<bool>("IsCompacting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compacting")
                        .HasJsonPropertyName("is_compacting");

                    b.Property<long?>("ParentSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_session_id")
                        .HasJsonPropertyName("parent_session_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary")
                        .HasJsonPropertyName("summary");

                    b.Property<Vector>("SummaryEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("summary_embedding")
                        .HasJsonPropertyName("summary_embedding");

                    b.Property<long?>("ToolsPrunedThroughId")
                        .HasColumnType("bigint")
                        .HasColumnName("tools_pruned_through_id")
                        .HasJsonPropertyName("tools_pruned_through_id");

                    b.Property<long>("TotalCacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cache_creation_tokens")
                        .HasJsonPropertyName("total_cache_creation_tokens");

                    b.Property<long>("TotalCacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cache_read_tokens")
                        .HasJsonPropertyName("total_cache_read_tokens");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_input_tokens")
                        .HasJsonPropertyName("total_input_tokens");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_output_tokens")
                        .HasJsonPropertyName("total_output_tokens");

                    b.Property<long>("TotalThinkingTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("total_thinking_tokens")
                        .HasJsonPropertyName("total_thinking_tokens");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ParentSessionId");

                    b.HasIndex("SummaryEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SummaryEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SummaryEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("session");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.SkillEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id")
                        .HasJsonPropertyName("agent_id");

                    b.Property<string>("AssetsPath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("assets_path")
                        .HasJsonPropertyName("assets_path");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasJsonPropertyName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled")
                        .HasJsonPropertyName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("source_url")
                        .HasJsonPropertyName("source_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasJsonPropertyName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Name")
                        .IsUnique();

                    b.ToTable("skill");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ToolDigestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("digest")
                        .HasJsonPropertyName("digest");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id")
                        .HasJsonPropertyName("message_id");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasJsonPropertyName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("tool_digest");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatAllowedSenderEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ChatEntity", "Chat")
                        .WithMany("AllowedSenders")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.AgentEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "CurrentSession")
                        .WithMany()
                        .HasForeignKey("CurrentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("CurrentSession");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactIdentifierEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ContactEntity", "Contact")
                        .WithMany("Identifiers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ExecAllowlistEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.AgentEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ExecApprovalEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.AgentEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lis.Persistence.Entities.ChatEntity", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MemoryEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.AgentEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lis.Persistence.Entities.ContactEntity", "Contact")
                        .WithMany("Memories")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.MessageEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.PromptSectionEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.AgentEntity", "Agent")
                        .WithMany("PromptSections")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.ChatEntity", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "ParentSession")
                        .WithMany()
                        .HasForeignKey("ParentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chat");

                    b.Navigation("ParentSession");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.SkillEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.AgentEntity", "Agent")
                        .WithMany("Skills")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ToolDigestEntity", b =>
                {
                    b.HasOne("Lis.Persistence.Entities.MessageEntity", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lis.Persistence.Entities.SessionEntity", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.AgentEntity", b =>
                {
                    b.Navigation("PromptSections");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ChatEntity", b =>
                {
                    b.Navigation("AllowedSenders");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lis.Persistence.Entities.ContactEntity", b =>
                {
                    b.Navigation("Identifiers");

                    b.Navigation("Memories");
                });
#pragma warning restore 612, 618
        }
    }
}
